// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL4_we0lWrpl8PJBo41e6hcBXO7feP8r0',
    appId: '1:983373087656:android:d63a14a52e018f45b1d39d',
    messagingSenderId: '983373087656',
    projectId: 'extreme-chess',
    storageBucket: 'extreme-chess.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByOaxpJeR4CmFSYy1TPhkkI-0tM65NAbY',
    appId: '1:983373087656:ios:cd58acbd20c6cf00b1d39d',
    messagingSenderId: '983373087656',
    projectId: 'extreme-chess',
    storageBucket: 'extreme-chess.appspot.com',
    androidClientId: '983373087656-cp712rl2ij281ae18k6p94e5scadcb25.apps.googleusercontent.com',
    iosClientId: '983373087656-rgsf3igenhar0nmdjlped141t4c090om.apps.googleusercontent.com',
    iosBundleId: 'xyz.arcyuniq.extremechess.extremeChessV2',
  );
}
